### ISSUE TITLE
T6000 CoreML samples needed

### ISSUE THREAD

**Issue by eiln** [eiln/anecc#1]
~~From any [T600X machine](https://github.com/AsahiLinux/docs/wiki/Devices) on Pre-Ventura MacOS.~~

Still need **T600X ane1/ane2/ane3 (M1 Max/Ultra)** & ~~M2 ane/ane0~~.
See [ANE Boards](https://gist.github.com/eiln/82406a83dc94019d7ffaed7d2e04f120).

`pip install coremltools` then run:

```
import coremltools as ct  # pip install coremltools
from coremltools.converters.mil import Builder as mb
@mb.program(input_specs=[mb.TensorSpec(shape=(123, 456)), mb.TensorSpec(shape=(456, 789)),])
def matmul(x, y):
    x = mb.matmul(x=x, y=y)
    return x
mlmodel = ct.convert(matmul)
mlmodel.save("matmul.mlmodel")
```

Install `coreml2hwx` with:

```
git clone https://github.com/eiln/coreml_to_ane_hwx
cd coreml_to_ane_hwx
make
sudo make install
```

Convert mlmodel -> hwx using `coreml2hwx matmul.mlmodel`

Which should output something like:

```
2023-02-15 10:45:59.466 coreml2hwx[986:9634] original mlmodel file: file:///Users/eileen/mobilenet.mlmodel 
2023-02-15 10:45:59.602 coreml2hwx[986:9634] espresso model in mlmodelc directory: /var/folders/wl/v5_h4f8x7ddc0cr8cpzb0clm0000gn/T/mobilenet.mlmodelc/model.espresso.net 
2023-02-15 10:45:59.902 coreml2hwx[986:9634] options:
{
    InputNetworks =     (
                {
            NetworkPlistName = "net.plist";
            NetworkPlistPath = "/tmp/espresso_ir_dump/";
        }
    );
    OutputFileName = "model.hwx";
    OutputFilePath = "/tmp/hwx_output/mobilenet/";
}
2023-02-15 10:45:59.902 coreml2hwx[986:9634] result at /tmp/hwx_output/mobilenet/model.hwx
```

**Please attach the resulting "model.hwx" file & device info.**

Or email (eyn@gmx.com) or some [public file-sharing site](https://www.file.io/).

Thanks all.

**Comment by WhatAmISupposedToPutHere** [comment]
Trying to run it on a j314s, macos 12.3, getting an error:
```
Python 3.8.9 (default, Apr 13 2022, 08:48:06) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import coremltools as ct  # pip install coremltools
>>> from coremltools.converters.mil import Builder as mb
>>> @mb.program(input_specs=[mb.TensorSpec(shape=(5, 65)), mb.TensorSpec(shape=(123, 456)),])
... def matmul(x, y):
...     x = mb.matmul(x=x, y=y)
...     return x
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/<cut>/venv/lib/python3.8/site-packages/coremltools/converters/mil/mil/builder.py", line 237, in wrapper
    outputs = main_block(*input_vars)
  File "<stdin>", line 3, in matmul
  File "/Users/<cut>/venv/lib/python3.8/site-packages/coremltools/converters/mil/mil/ops/registry.py", line 176, in add_op
    return cls._add_op(op_cls_to_add, **kwargs)
  File "/Users/<cut>/venv/lib/python3.8/site-packages/coremltools/converters/mil/mil/builder.py", line 182, in _add_op
    new_op.type_value_inference()
  File "/Users/<cut>/venv/lib/python3.8/site-packages/coremltools/converters/mil/mil/operation.py", line 253, in type_value_inference
    output_types = self.type_inference()
  File "/Users/<cut>/venv/lib/python3.8/site-packages/coremltools/converters/mil/mil/ops/defs/iOS15/linear.py", line 202, in type_inference
    raise ValueError(msg.format(self.name, self.x.shape, self.y.shape))
ValueError: Op matmul_0 (matmul): x (5, 65), y (123, 456) are not broadcastable
```

**Comment by povik** [comment]
Same here

**Comment by povik** [comment]
Changing the shape from (5, 65) to (5, 123) on the first input, this is the `model.hwx` I got on j314s. (It's gzipped to make github happy.)
[model.hwx.gz](https://github.com/eiln/anecc/files/11076814/model.hwx.gz)

**Comment by eiln** [comment]
Ah copy pasted the wrong function, fixed.

**Comment by povik** [comment]
Is the shape I tried ok, or should I rerun?

**Comment by eiln** [comment]
@povik Works, thank you.

**Comment by povik** [comment]
Happy to!

**Comment by eiln** [comment]
@WhatAmISupposedToPutHere  Sorry, copy-pasted the wrong numbers. Updated.

**Comment by WhatAmISupposedToPutHere** [comment]
since i also only have a j314s, do you need another copy of the model? or povik's is enough?

**Comment by eiln** [comment]
ane0 uses the identical compiler flags and works OOTB. Whew. I just need ane1/ane2/ane3 now. Thank you though.

**Comment by rowanG077** [comment]
@eiln 

I do have an M2 Max(30 GPU cores version) but it's running Ventura I could downgrade but I would like to avoid that if possible. Does it really require pre-ventura?

**Comment by eiln** [comment]
@rowanG077 No it's fine. The model is simple enough to not trigger new firmware APIs.

**Comment by rowanG077** [comment]
@eiln See attachment.

Device Info: M2 Max 30 GPU cores
OS: Ventura (13.0)

[](url)
[model.hwx.zip](https://github.com/eiln/anecc/files/11092446/model.hwx.zip)

**Comment by eiln** [comment]
@rowanG077 Thank you. Looks different as expected, investigating now...

**Comment by eiln** [comment]
@rowanG077 Tiny patch and M2 also works https://github.com/eiln/anecc/commit/4c3343043fc2194b6750633a9cb734d3f835d035.

**Comment by topias** [comment]
Device Info: MacBook Pro 14-inch, M1 Max, 2021, 24 GPU cores
OS: Ventura 13.2.1

[model.hwx.gz](https://github.com/eiln/anecc/files/11129906/model.hwx.gz)

**Comment by eiln** [comment]
@topias Thank you! Also works OOTB.
